/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    'product-types': ProductType;
    'attribute-definitions': AttributeDefinition;
    products: Product;
    'product-variants': ProductVariant;
    'product-offers': ProductOffer;
    'product-inventory': ProductInventory;
    'product-ai-metadata': ProductAiMetadatum;
    'scraper-jobs': ScraperJob;
    orders: Order;
    banners: Banner;
    solutions: Solution;
    'post-categories': PostCategory;
    'post-tags': PostTag;
    'news-redirects': NewsRedirect;
    posts: Post;
    certifications: Certification;
    'project-categories': ProjectCategory;
    'download-categories': DownloadCategory;
    downloads: Download;
    projects: Project;
    faq: Faq;
    testimonials: Testimonial;
    'static-pages': StaticPage;
    'enterprise-services': EnterpriseService;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'product-types': ProductTypesSelect<false> | ProductTypesSelect<true>;
    'attribute-definitions': AttributeDefinitionsSelect<false> | AttributeDefinitionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    'product-offers': ProductOffersSelect<false> | ProductOffersSelect<true>;
    'product-inventory': ProductInventorySelect<false> | ProductInventorySelect<true>;
    'product-ai-metadata': ProductAiMetadataSelect<false> | ProductAiMetadataSelect<true>;
    'scraper-jobs': ScraperJobsSelect<false> | ScraperJobsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'post-tags': PostTagsSelect<false> | PostTagsSelect<true>;
    'news-redirects': NewsRedirectsSelect<false> | NewsRedirectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    'download-categories': DownloadCategoriesSelect<false> | DownloadCategoriesSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    'enterprise-services': EnterpriseServicesSelect<false> | EnterpriseServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'about-page': AboutPage;
    'enterprise-support-page': EnterpriseSupportPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'enterprise-support-page': EnterpriseSupportPageSelect<false> | EnterpriseSupportPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Tên thư mục logic, không phải đường dẫn trên máy chủ.
   */
  folder?: string | null;
  /**
   * Ví dụ: banner, product, logo
   */
  tags?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  parent?: (number | null) | Category;
  description?: string | null;
  /**
   * Ví dụ: printer, scan-line, hard-drive
   */
  icon?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  website?: string | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types".
 */
export interface ProductType {
  id: number;
  code: 'scanner' | 'printer' | 'photocopier' | 'laptop' | 'software' | 'ink' | 'networking' | 'camera' | 'other';
  name: string;
  description?: string | null;
  schemaVersion: number;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-definitions".
 */
export interface AttributeDefinition {
  id: number;
  productType: number | ProductType;
  /**
   * Mã ổn định cho máy đọc, ví dụ: scan_speed_simplex.
   */
  code: string;
  label: string;
  dataType: 'number' | 'text' | 'boolean' | 'enum' | 'enum_list';
  unit:
    | 'none'
    | 'ppm'
    | 'ipm'
    | 'cpm'
    | 'sheets'
    | 'pages_per_day'
    | 'pages_per_month'
    | 'dpi'
    | 'mm'
    | 'inch'
    | 'hz'
    | 'kg'
    | 'mb'
    | 'gb'
    | 'w'
    | 'v'
    | 'percent';
  /**
   * Bắt buộc với kiểu enum và enum_list.
   */
  options?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  required?: boolean | null;
  searchable?: boolean | null;
  comparable?: boolean | null;
  filterable?: boolean | null;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Sản phẩm cũ giữ legacy đến khi migration. Sản phẩm mới phải dùng Catalog chuẩn.
   */
  dataModel: 'canonical' | 'legacy';
  /**
   * Định danh ổn định của Product, tự sinh khi tạo mới. Không dùng tên sản phẩm.
   */
  internalId?: string | null;
  productType?: (number | null) | ProductType;
  /**
   * Tên chính thức của model. Field này đồng bộ sang Tên sản phẩm legacy.
   */
  name?: string | null;
  /**
   * Manufacturer Part Number, chỉ nhập mã do hãng công bố.
   */
  mpn?: string | null;
  source: {
    type: 'manual' | 'manufacturer' | 'scraper' | 'import';
    verified?: boolean | null;
    url?: string | null;
    verifiedAt?: string | null;
  };
  /**
   * Nội dung ngắn có cấu trúc cho catalog, báo giá và các kênh tích hợp.
   */
  shortDescription?: string | null;
  /**
   * Chọn định nghĩa thuộc tính và nhập đúng cột giá trị theo kiểu dữ liệu.
   */
  attributes?:
    | {
        definition: number | AttributeDefinition;
        dataType: 'number' | 'text' | 'boolean' | 'enum' | 'enum_list';
        unit:
          | 'none'
          | 'ppm'
          | 'ipm'
          | 'cpm'
          | 'sheets'
          | 'pages_per_day'
          | 'pages_per_month'
          | 'dpi'
          | 'mm'
          | 'inch'
          | 'hz'
          | 'kg'
          | 'mb'
          | 'gb'
          | 'w'
          | 'v'
          | 'percent';
        numberValue?: number | null;
        textValue?: string | null;
        booleanValue?: boolean | null;
        /**
         * Nhập value đã định nghĩa trong Attribute Definition.
         */
        enumValue?: string | null;
        enumListValue?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Tùy chọn. Lưu chuỗi từ datasheet để truy vết, không dùng để filter.
         */
        rawValue?: string | null;
        id?: string | null;
      }[]
    | null;
  title: string;
  /**
   * Ví dụ: HL-L2366DW
   */
  sku?: string | null;
  /**
   * Ví dụ: ADS-4300N, DS-790WN, LaserJet 4003dn.
   */
  model?: string | null;
  /**
   * Đường dẫn thân thiện dùng trên website.
   */
  slug: string;
  brand: number | Brand;
  stockStatus?: ('in_stock' | 'out_of_stock' | 'preorder') | null;
  /**
   * Nhập theo định dạng hiển thị, ví dụ: 3.900.000đ.
   */
  price?: string | null;
  compareAtPrice?: string | null;
  vatIncluded?: boolean | null;
  /**
   * Từ 0 đến 5 sao.
   */
  rating?: number | null;
  reviewCount?: number | null;
  viewCount?: number | null;
  /**
   * Ví dụ: Giảm 15%, Quà tặng, Hot deal.
   */
  discountBadge?: string | null;
  promoText?: string | null;
  promoStart?: string | null;
  promoEnd?: string | null;
  /**
   * Ví dụ: 12 tháng.
   */
  warranty?: string | null;
  origin?: string | null;
  /**
   * Hiển thị ở danh sách và phần đầu trang sản phẩm.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  summaryHTML?: string | null;
  /**
   * Các gạch đầu dòng nổi bật hiển thị ở khối đầu trang sản phẩm.
   */
  sellingPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  tag?: ('Mới' | 'Bán chạy' | 'Cao cấp' | 'Khuyến mãi') | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Nội dung chính hiển thị ở trang chi tiết sản phẩm.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionHTML?: string | null;
  /**
   * Hướng dẫn lắp đặt, vận hành hoặc lưu ý khi sử dụng sản phẩm.
   */
  usageGuide?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  usageGuideHTML?: string | null;
  /**
   * CMS sẽ ưu tiên tự hiện bộ field theo Danh mục đã chọn ở sidebar. Nếu danh mục chưa nhận diện được, chọn thủ công tại đây.
   */
  specProfile?:
    | ('scanner' | 'printer' | 'photocopier' | 'laptop' | 'networking' | 'camera' | 'software' | 'other')
    | null;
  /**
   * Các trường chuẩn dành riêng cho máy scan. Nhân viên nhập theo datasheet để AI Search lọc đúng tốc độ, ADF, kết nối và nhu cầu sử dụng.
   */
  scannerSpecs?: {
    /**
     * Ví dụ: ADF, Flatbed, ADF + Flatbed, Sheet-fed.
     */
    scannerType?: string | null;
    /**
     * Ví dụ: scan 2 mặt, scan màu, OCR, scan thẻ.
     */
    functions?: string | null;
    /**
     * Nhập số tờ/phút hoặc ppm. Ví dụ: 40.
     */
    scanSpeedSimplexPpm?: number | null;
    /**
     * Nhập số ảnh/phút hoặc ipm. Ví dụ: 80.
     */
    scanSpeedDuplexIpm?: number | null;
    /**
     * Ví dụ: màu, xám, đen trắng, tự động 2 mặt.
     */
    scanModes?: string | null;
    /**
     * Ví dụ: 600 x 600 dpi.
     */
    scanResolution?: string | null;
    /**
     * Ví dụ: LED, LCD, màn hình cảm ứng.
     */
    displayScreen?: string | null;
    /**
     * Ví dụ: CMOS, CIS, CCD.
     */
    scanTechnology?: string | null;
    /**
     * Sức chứa khay nạp tự động, ví dụ: 80.
     */
    adfSheets?: number | null;
    /**
     * Nếu khác với ADF, nhập số tờ tối đa.
     */
    adfCapacitySheets?: number | null;
    /**
     * Ví dụ: A4, Legal, A3.
     */
    maxPaperSize?: string | null;
    minPaperSize?: string | null;
    /**
     * Ví dụ: 4000.
     */
    dailyDuty?: number | null;
    /**
     * Ví dụ: Có, Không, hỗ trợ scan hộ chiếu.
     */
    passportScanText?: string | null;
    /**
     * Ví dụ: Có, Không, tự động hai mặt.
     */
    duplexScanText?: string | null;
    /**
     * Ví dụ: Có, Không, màu/xám/đen trắng.
     */
    colorScanText?: string | null;
    /**
     * Ví dụ: Có, Không, OCR tiếng Việt/tiếng Anh.
     */
    ocrText?: string | null;
    /**
     * Ví dụ: Có, Không, thẻ ID/card nhựa.
     */
    plasticCardScanText?: string | null;
    /**
     * Ví dụ: USB 3.0, LAN, WiFi.
     */
    connectivity?: string | null;
    /**
     * Ví dụ: Windows, macOS, Linux.
     */
    supportedOs?: string | null;
    /**
     * Ví dụ: 454 x 331 x 129 mm.
     */
    dimensions?: string | null;
    /**
     * Ví dụ: 4.3 kg.
     */
    weight?: string | null;
    dimensionsWeight?: string | null;
    passportScan?: boolean | null;
    duplexScan?: boolean | null;
    colorScan?: boolean | null;
    ocr?: boolean | null;
    plasticCardScan?: boolean | null;
  };
  /**
   * Các trường chuẩn dành riêng cho máy in. Nhập dạng text theo datasheet để tránh sai đơn vị hoặc thiếu ghi chú kỹ thuật.
   */
  printerSpecs?: {
    /**
     * Ví dụ: laser trắng đen, laser màu, phun màu, đa năng.
     */
    printerType?: string | null;
    /**
     * Ví dụ: in, copy, scan, fax.
     */
    functions?: string | null;
    /**
     * Ví dụ: Laser, Inkjet, LED.
     */
    printTechnology?: string | null;
    /**
     * Ví dụ: 40 trang/phút, 40 ppm.
     */
    printSpeed?: string | null;
    /**
     * Ví dụ: 1200 x 1200 dpi.
     */
    printResolution?: string | null;
    /**
     * Ví dụ: A4, A3.
     */
    maxPaperSize?: string | null;
    /**
     * Ví dụ: Có, Không, In màu laser.
     */
    colorPrintText?: string | null;
    /**
     * Ví dụ: Có, Không, Duplex tự động.
     */
    autoDuplexPrintText?: string | null;
    /**
     * Ví dụ: 250 tờ.
     */
    standardPaperTray?: string | null;
    /**
     * Ví dụ: 900 tờ.
     */
    maxPaperTray?: string | null;
    /**
     * Ví dụ: 256MB, 1GB.
     */
    memoryRam?: string | null;
    /**
     * Ví dụ: USB, LAN, WiFi.
     */
    connectivity?: string | null;
    supportedOs?: string | null;
    /**
     * Ví dụ: 750 - 4.000 trang/tháng.
     */
    recommendedMonthlyVolumeText?: string | null;
    /**
     * Ví dụ: 80.000 trang/tháng.
     */
    maxMonthlyDuty?: string | null;
    /**
     * Ví dụ: 356 x 360 x 183 mm.
     */
    dimensions?: string | null;
    /**
     * Ví dụ: 7,2 kg.
     */
    weight?: string | null;
    printSpeedPpm?: number | null;
    colorPrint?: boolean | null;
    autoDuplexPrint?: boolean | null;
    standardPaperTraySheets?: number | null;
    maxPaperTraySheets?: number | null;
    monthlyDuty?: number | null;
    recommendedMonthlyVolume?: number | null;
    dimensionsWeight?: string | null;
    inkType?: string | null;
  };
  /**
   * Các trường chuẩn dành riêng cho máy photocopy. Nhập dạng text theo datasheet để tránh sai đơn vị hoặc thiếu ghi chú kỹ thuật.
   */
  photocopierSpecs?: {
    /**
     * Ví dụ: photocopy A3, A4, màu, đen trắng.
     */
    copierType?: string | null;
    /**
     * Ví dụ: copy, in, scan, fax.
     */
    functions?: string | null;
    /**
     * Ví dụ: 35 bản/phút.
     */
    copySpeed?: string | null;
    /**
     * Ví dụ: 35 trang/phút.
     */
    printSpeed?: string | null;
    /**
     * Ví dụ: 80 ảnh/phút.
     */
    scanSpeed?: string | null;
    /**
     * Ví dụ: A3, A4.
     */
    maxPaperSize?: string | null;
    /**
     * Ví dụ: 600 x 600 dpi.
     */
    copyResolution?: string | null;
    printResolution?: string | null;
    scanResolution?: string | null;
    /**
     * Ví dụ: Có, Không.
     */
    colorPrintText?: string | null;
    /**
     * Ví dụ: Có, Không, Duplex tự động.
     */
    autoDuplexPrintText?: string | null;
    /**
     * Ví dụ: Có, Không, DADF/RADF.
     */
    adfText?: string | null;
    /**
     * Ví dụ: 100 tờ.
     */
    adfCapacity?: string | null;
    memoryRam?: string | null;
    /**
     * Ví dụ: LAN, USB, WiFi.
     */
    connectivity?: string | null;
    /**
     * Ví dụ: 100.000 bản/tháng.
     */
    monthlyDuty?: string | null;
    dimensionsWeight?: string | null;
    copySpeedCpm?: number | null;
    scanSpeedPpm?: number | null;
    colorPrint?: boolean | null;
    colorScan?: boolean | null;
    autoDuplexPrint?: boolean | null;
    hasAdf?: boolean | null;
    adfSheets?: number | null;
    standardPaperTraySheets?: number | null;
    maxPaperTraySheets?: number | null;
  };
  /**
   * Các trường chuẩn hóa để lọc nhanh laptop. Raw specs từ nguồn vẫn được lưu đầy đủ ở bảng thông số kỹ thuật.
   */
  laptopSpecs?: {
    /**
     * Ví dụ: Intel Core 7 240H.
     */
    cpu?: string | null;
    /**
     * Ví dụ: NVIDIA GeForce RTX 5060 8GB.
     */
    gpu?: string | null;
    /**
     * Ví dụ: 16GB DDR5.
     */
    ram?: string | null;
    /**
     * Ví dụ: 1TB SSD NVMe.
     */
    storage?: string | null;
    /**
     * Ví dụ: 16 inch WUXGA 144Hz.
     */
    screen?: string | null;
    /**
     * Ví dụ: WUXGA, 1920 x 1200.
     */
    screenResolution?: string | null;
    /**
     * Đơn vị inch, ví dụ: 16.
     */
    screenSizeInch?: number | null;
    /**
     * Đơn vị Hz, ví dụ: 144.
     */
    refreshRateHz?: number | null;
    /**
     * Ví dụ: IPS, OLED.
     */
    panel?: string | null;
    /**
     * Ví dụ: Windows 11.
     */
    os?: string | null;
    /**
     * Ví dụ: WiFi, Bluetooth, USB-C, HDMI.
     */
    connectivity?: string | null;
    battery?: string | null;
    dimensions?: string | null;
    weight?: string | null;
    ramGb?: number | null;
    storageGb?: number | null;
  };
  /**
   * Lưu nguyên các thông số lấy được từ trang nguồn, không bắt buộc theo bộ cột cố định.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dùng cho PDF catalogue, datasheet hoặc tài liệu hướng dẫn.
   */
  datasheets?: (number | Media)[] | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * Số nhỏ hơn được ưu tiên hiển thị trước khi cần sắp xếp thủ công.
   */
  sortOrder?: number | null;
  /**
   * Chỉ dùng trong CMS, không hiển thị ngoài website.
   */
  internalNote?: string | null;
  category: number | Category;
  /**
   * Khuyến nghị ảnh vuông 1200x1200px.
   */
  images?: (number | Media)[] | null;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  sku: string;
  product: number | Product;
  /**
   * Ví dụ: Bản tiêu chuẩn, kèm ADF, màu trắng.
   */
  variantName: string;
  barcode?: string | null;
  warranty?: string | null;
  isPrimary?: boolean | null;
  status: 'draft' | 'active' | 'discontinued';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-offers".
 */
export interface ProductOffer {
  id: number;
  variant: number | ProductVariant;
  price: number;
  currency: 'VND' | 'USD';
  vatRate: number;
  vatIncluded?: boolean | null;
  promotionPrice?: number | null;
  validFrom?: string | null;
  validTo?: string | null;
  saleStatus: 'active' | 'contact' | 'paused' | 'discontinued';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-inventory".
 */
export interface ProductInventory {
  id: number;
  variant: number | ProductVariant;
  warehouseName: string;
  quantity: number;
  stockStatus: 'unknown' | 'in_stock' | 'out_of_stock' | 'preorder';
  updatedAt: string;
  note?: string | null;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-ai-metadata".
 */
export interface ProductAiMetadatum {
  id: number;
  product: number | Product;
  useCases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  competitorModels?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  aiGenerated?: boolean | null;
  verified?: boolean | null;
  verifiedAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-jobs".
 */
export interface ScraperJob {
  id: number;
  query: string;
  brandDetected?: string | null;
  sourceUrl?: string | null;
  searchQuery?: string | null;
  reviewStatus?: ('ready_to_review' | 'needs_human_input' | 'approved' | 'published' | 'failed') | null;
  confidence?: number | null;
  warnings?:
    | {
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  rawExtractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seoPreview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productCreated?: (number | null) | Product;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderCode: string;
  status: 'new' | 'contacting' | 'confirmed' | 'processing' | 'completed' | 'cancelled';
  customerName: string;
  customerPhone: string;
  customerEmail?: string | null;
  customerArea?: string | null;
  customerAddress: string;
  customerNote?: string | null;
  paymentMethod: 'cod' | 'confirm_first';
  shippingFeeStatus: 'pending_confirmation';
  items: {
    product?: (number | null) | Product;
    slug?: string | null;
    href?: string | null;
    title: string;
    brand?: string | null;
    category?: string | null;
    image?: string | null;
    priceLabel?: string | null;
    unitPrice?: number | null;
    quantity: number;
    lineTotal?: number | null;
    requiresPriceConfirmation?: boolean | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  totalLabel: string;
  requiresPriceConfirmation?: boolean | null;
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  image: number | Media;
  title?: string | null;
  subtitle?: string | null;
  link?: string | null;
  sortOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  name: string;
  slug: string;
  /**
   * Ví dụ: printer, scan-line, shield, blocks
   */
  icon?: string | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedProducts?: (number | Product)[] | null;
  image?: (number | null) | Media;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  name: string;
  slug: string;
  /**
   * Để trống nếu đây là danh mục cha cấp cao.
   */
  parent?: (number | null) | PostCategory;
  fullTitle?: string | null;
  fullSlug?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-tags".
 */
export interface PostTag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-redirects".
 */
export interface NewsRedirect {
  id: number;
  /**
   * Không bao gồm /tin-tuc/. Ví dụ: thiet-bi/may-in/bai-cu
   */
  fromPath: string;
  /**
   * Không bao gồm /tin-tuc/. Ví dụ: thiet-bi/may-in/bai-moi
   */
  toPath: string;
  statusCode: '301' | '302';
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * Ví dụ: thiet-bi-giai-phap-van-phong/may-in/may-in-hp-bi-ket-giay
   */
  fullPath?: string | null;
  thumbnail?: (number | null) | Media;
  publishedAt?: string | null;
  author?: (number | null) | User;
  /**
   * Chọn danh mục con cuối cùng. Danh mục hiển thị dạng Cha > Con.
   */
  category: number | PostCategory;
  tags?: (number | PostTag)[] | null;
  postType: 'news' | 'guide' | 'case-study' | 'announcement' | 'recruitment';
  featured?: boolean | null;
  relatedProducts?: (number | Product)[] | null;
  summary?: string | null;
  /**
   * Tự động tăng khi người dùng mở bài viết.
   */
  viewCount?: number | null;
  guideMeta?: {
    difficulty?: ('basic' | 'intermediate' | 'advanced') | null;
    estimatedTime?: string | null;
    appliesTo?: string | null;
  };
  caseStudyMeta?: {
    industry?: string | null;
    clientName?: string | null;
    clientType?: string | null;
    challenge?: string | null;
    solution?: string | null;
    result?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  brand: string;
  /**
   * Để trống sẽ tự sinh từ tên thương hiệu. Ví dụ: microtek.
   */
  slug: string;
  kind: 'doc-quyen' | 'doi-tac' | 'uy-quyen';
  /**
   * Ví dụ: "Nhà phân phối độc quyền".
   */
  kindLabel: string;
  image: number | Media;
  logo?: (number | null) | Media;
  scope?: string | null;
  territory?: string | null;
  validFrom?: string | null;
  validTo?: string | null;
  issuer?: string | null;
  certNo?: string | null;
  /**
   * Dùng cho card và meta description.
   */
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-categories".
 */
export interface DownloadCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  slug: string;
  category: number | DownloadCategory;
  brand?: (number | null) | Brand;
  products?: (number | Product)[] | null;
  model?: string | null;
  version?: string | null;
  file?: (number | null) | Media;
  /**
   * Dùng khi file nằm trên website hãng sản xuất.
   */
  externalUrl?: string | null;
  publishedAt?: string | null;
  summary?: string | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug: string;
  client?: string | null;
  category?: (number | null) | ProjectCategory;
  industry?: string | null;
  completedAt?: string | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  products?: (number | Product)[] | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  company?: string | null;
  content?: string | null;
  rating?: number | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  title: string;
  slug: string;
  eyebrow?: string | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-services".
 */
export interface EnterpriseService {
  id: number;
  title: string;
  slug: string;
  summary: string;
  icon?: ('scan' | 'file' | 'network' | 'camera' | 'wrench' | 'building' | 'school' | 'server') | null;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Thông tin SEO dùng cho trang public và danh mục.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  sortOrder?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'product-types';
        value: number | ProductType;
      } | null)
    | ({
        relationTo: 'attribute-definitions';
        value: number | AttributeDefinition;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'product-offers';
        value: number | ProductOffer;
      } | null)
    | ({
        relationTo: 'product-inventory';
        value: number | ProductInventory;
      } | null)
    | ({
        relationTo: 'product-ai-metadata';
        value: number | ProductAiMetadatum;
      } | null)
    | ({
        relationTo: 'scraper-jobs';
        value: number | ScraperJob;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'post-tags';
        value: number | PostTag;
      } | null)
    | ({
        relationTo: 'news-redirects';
        value: number | NewsRedirect;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'download-categories';
        value: number | DownloadCategory;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'static-pages';
        value: number | StaticPage;
      } | null)
    | ({
        relationTo: 'enterprise-services';
        value: number | EnterpriseService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  tags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  icon?: T;
  image?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  website?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types_select".
 */
export interface ProductTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  schemaVersion?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-definitions_select".
 */
export interface AttributeDefinitionsSelect<T extends boolean = true> {
  productType?: T;
  code?: T;
  label?: T;
  dataType?: T;
  unit?: T;
  options?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  required?: T;
  searchable?: T;
  comparable?: T;
  filterable?: T;
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  dataModel?: T;
  internalId?: T;
  productType?: T;
  name?: T;
  mpn?: T;
  source?:
    | T
    | {
        type?: T;
        verified?: T;
        url?: T;
        verifiedAt?: T;
      };
  shortDescription?: T;
  attributes?:
    | T
    | {
        definition?: T;
        dataType?: T;
        unit?: T;
        numberValue?: T;
        textValue?: T;
        booleanValue?: T;
        enumValue?: T;
        enumListValue?:
          | T
          | {
              value?: T;
              id?: T;
            };
        rawValue?: T;
        id?: T;
      };
  title?: T;
  sku?: T;
  model?: T;
  slug?: T;
  brand?: T;
  stockStatus?: T;
  price?: T;
  compareAtPrice?: T;
  vatIncluded?: T;
  rating?: T;
  reviewCount?: T;
  viewCount?: T;
  discountBadge?: T;
  promoText?: T;
  promoStart?: T;
  promoEnd?: T;
  warranty?: T;
  origin?: T;
  summary?: T;
  summaryHTML?: T;
  sellingPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tag?: T;
  relatedProducts?: T;
  description?: T;
  descriptionHTML?: T;
  usageGuide?: T;
  usageGuideHTML?: T;
  specProfile?: T;
  scannerSpecs?:
    | T
    | {
        scannerType?: T;
        functions?: T;
        scanSpeedSimplexPpm?: T;
        scanSpeedDuplexIpm?: T;
        scanModes?: T;
        scanResolution?: T;
        displayScreen?: T;
        scanTechnology?: T;
        adfSheets?: T;
        adfCapacitySheets?: T;
        maxPaperSize?: T;
        minPaperSize?: T;
        dailyDuty?: T;
        passportScanText?: T;
        duplexScanText?: T;
        colorScanText?: T;
        ocrText?: T;
        plasticCardScanText?: T;
        connectivity?: T;
        supportedOs?: T;
        dimensions?: T;
        weight?: T;
        dimensionsWeight?: T;
        passportScan?: T;
        duplexScan?: T;
        colorScan?: T;
        ocr?: T;
        plasticCardScan?: T;
      };
  printerSpecs?:
    | T
    | {
        printerType?: T;
        functions?: T;
        printTechnology?: T;
        printSpeed?: T;
        printResolution?: T;
        maxPaperSize?: T;
        colorPrintText?: T;
        autoDuplexPrintText?: T;
        standardPaperTray?: T;
        maxPaperTray?: T;
        memoryRam?: T;
        connectivity?: T;
        supportedOs?: T;
        recommendedMonthlyVolumeText?: T;
        maxMonthlyDuty?: T;
        dimensions?: T;
        weight?: T;
        printSpeedPpm?: T;
        colorPrint?: T;
        autoDuplexPrint?: T;
        standardPaperTraySheets?: T;
        maxPaperTraySheets?: T;
        monthlyDuty?: T;
        recommendedMonthlyVolume?: T;
        dimensionsWeight?: T;
        inkType?: T;
      };
  photocopierSpecs?:
    | T
    | {
        copierType?: T;
        functions?: T;
        copySpeed?: T;
        printSpeed?: T;
        scanSpeed?: T;
        maxPaperSize?: T;
        copyResolution?: T;
        printResolution?: T;
        scanResolution?: T;
        colorPrintText?: T;
        autoDuplexPrintText?: T;
        adfText?: T;
        adfCapacity?: T;
        memoryRam?: T;
        connectivity?: T;
        monthlyDuty?: T;
        dimensionsWeight?: T;
        copySpeedCpm?: T;
        scanSpeedPpm?: T;
        colorPrint?: T;
        colorScan?: T;
        autoDuplexPrint?: T;
        hasAdf?: T;
        adfSheets?: T;
        standardPaperTraySheets?: T;
        maxPaperTraySheets?: T;
      };
  laptopSpecs?:
    | T
    | {
        cpu?: T;
        gpu?: T;
        ram?: T;
        storage?: T;
        screen?: T;
        screenResolution?: T;
        screenSizeInch?: T;
        refreshRateHz?: T;
        panel?: T;
        os?: T;
        connectivity?: T;
        battery?: T;
        dimensions?: T;
        weight?: T;
        ramGb?: T;
        storageGb?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  datasheets?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  sortOrder?: T;
  internalNote?: T;
  category?: T;
  images?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  sku?: T;
  product?: T;
  variantName?: T;
  barcode?: T;
  warranty?: T;
  isPrimary?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-offers_select".
 */
export interface ProductOffersSelect<T extends boolean = true> {
  variant?: T;
  price?: T;
  currency?: T;
  vatRate?: T;
  vatIncluded?: T;
  promotionPrice?: T;
  validFrom?: T;
  validTo?: T;
  saleStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-inventory_select".
 */
export interface ProductInventorySelect<T extends boolean = true> {
  variant?: T;
  warehouseName?: T;
  quantity?: T;
  stockStatus?: T;
  updatedAt?: T;
  note?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-ai-metadata_select".
 */
export interface ProductAiMetadataSelect<T extends boolean = true> {
  product?: T;
  useCases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  competitorModels?:
    | T
    | {
        value?: T;
        id?: T;
      };
  aiGenerated?: T;
  verified?: T;
  verifiedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-jobs_select".
 */
export interface ScraperJobsSelect<T extends boolean = true> {
  query?: T;
  brandDetected?: T;
  sourceUrl?: T;
  searchQuery?: T;
  reviewStatus?: T;
  confidence?: T;
  warnings?:
    | T
    | {
        message?: T;
        id?: T;
      };
  rawExtractedData?: T;
  generatedContent?: T;
  seoPreview?: T;
  productCreated?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderCode?: T;
  status?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  customerArea?: T;
  customerAddress?: T;
  customerNote?: T;
  paymentMethod?: T;
  shippingFeeStatus?: T;
  items?:
    | T
    | {
        product?: T;
        slug?: T;
        href?: T;
        title?: T;
        brand?: T;
        category?: T;
        image?: T;
        priceLabel?: T;
        unitPrice?: T;
        quantity?: T;
        lineTotal?: T;
        requiresPriceConfirmation?: T;
        id?: T;
      };
  subtotal?: T;
  totalLabel?: T;
  requiresPriceConfirmation?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  subtitle?: T;
  link?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  summary?: T;
  content?: T;
  relatedProducts?: T;
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  fullTitle?: T;
  fullSlug?: T;
  description?: T;
  coverImage?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-tags_select".
 */
export interface PostTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-redirects_select".
 */
export interface NewsRedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  fullPath?: T;
  thumbnail?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  tags?: T;
  postType?: T;
  featured?: T;
  relatedProducts?: T;
  summary?: T;
  viewCount?: T;
  guideMeta?:
    | T
    | {
        difficulty?: T;
        estimatedTime?: T;
        appliesTo?: T;
      };
  caseStudyMeta?:
    | T
    | {
        industry?: T;
        clientName?: T;
        clientType?: T;
        challenge?: T;
        solution?: T;
        result?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  brand?: T;
  slug?: T;
  kind?: T;
  kindLabel?: T;
  image?: T;
  logo?: T;
  scope?: T;
  territory?: T;
  validFrom?: T;
  validTo?: T;
  issuer?: T;
  certNo?: T;
  summary?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-categories_select".
 */
export interface DownloadCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  brand?: T;
  products?: T;
  model?: T;
  version?: T;
  file?: T;
  externalUrl?: T;
  publishedAt?: T;
  summary?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  client?: T;
  category?: T;
  industry?: T;
  completedAt?: T;
  summary?: T;
  content?: T;
  gallery?: T;
  products?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  company?: T;
  content?: T;
  rating?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  summary?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-services_select".
 */
export interface EnterpriseServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  image?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  phone?: string | null;
  hotline?: string | null;
  email?: string | null;
  address?: string | null;
  facebook?: string | null;
  zalo?: string | null;
  youtube?: string | null;
  googleMapsTitle?: string | null;
  /**
   * Dán phần src trong iframe Google Maps Embed.
   */
  googleMapsEmbedUrl?: string | null;
  googleMapsDirectionsUrl?: string | null;
  googleAnalyticsId?: string | null;
  googleTagManagerId?: string | null;
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title: string;
    description: string;
    backgroundImage?: (number | null) | Media;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  sections?: {
    capabilitiesEyebrow?: string | null;
    capabilitiesTitle?: string | null;
    capabilitiesDescription?: string | null;
    processEyebrow?: string | null;
    processTitle?: string | null;
    processDescription?: string | null;
    partnersEyebrow?: string | null;
    partnersTitle?: string | null;
    partnersDescription?: string | null;
    advantagesEyebrow?: string | null;
    advantagesTitle?: string | null;
    advantagesDescription?: string | null;
    caseStudiesEyebrow?: string | null;
    caseStudiesTitle?: string | null;
    caseStudiesDescription?: string | null;
  };
  capabilities?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  caseStudies?:
    | {
        segment: string;
        title: string;
        summary?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  cta: {
    title: string;
    description?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-support-page".
 */
export interface EnterpriseSupportPage {
  id: number;
  /**
   * Tải tối đa 4 ảnh. Khi chưa có ảnh, website hiển thị icon mặc định.
   */
  heroImages?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  phone?: T;
  hotline?: T;
  email?: T;
  address?: T;
  facebook?: T;
  zalo?: T;
  youtube?: T;
  googleMapsTitle?: T;
  googleMapsEmbedUrl?: T;
  googleMapsDirectionsUrl?: T;
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        capabilitiesEyebrow?: T;
        capabilitiesTitle?: T;
        capabilitiesDescription?: T;
        processEyebrow?: T;
        processTitle?: T;
        processDescription?: T;
        partnersEyebrow?: T;
        partnersTitle?: T;
        partnersDescription?: T;
        advantagesEyebrow?: T;
        advantagesTitle?: T;
        advantagesDescription?: T;
        caseStudiesEyebrow?: T;
        caseStudiesTitle?: T;
        caseStudiesDescription?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  caseStudies?:
    | T
    | {
        segment?: T;
        title?: T;
        summary?: T;
        image?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enterprise-support-page_select".
 */
export interface EnterpriseSupportPageSelect<T extends boolean = true> {
  heroImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}