import type { Field, GlobalConfig } from "payload";
import { revalidateGlobal } from "../lib/payload/hooks/revalidate.ts";

export const defaultAboutPage = {
  hero: {
    title: "Đối tác công nghệ cho doanh nghiệp hiện đại",
    description:
      "HPT TECH cung cấp thiết bị công nghệ, dịch vụ kỹ thuật và giải pháp hạ tầng CNTT toàn diện, giúp doanh nghiệp vận hành hiệu quả và phát triển bền vững.",
    primaryCtaLabel: "Nhận tư vấn giải pháp",
    primaryCtaHref: "/lien-he",
    secondaryCtaLabel: "Khám phá dịch vụ",
    secondaryCtaHref: "/dich-vu",
  },
  stats: [
    { value: "15+", label: "Năm kinh nghiệm", description: "Đồng hành cùng doanh nghiệp" },
    { value: "5000+", label: "Khách hàng", description: "Đã tư vấn và hỗ trợ" },
    { value: "50+", label: "Thương hiệu", description: "Thiết bị và giải pháp" },
    { value: "Toàn quốc", label: "Triển khai & hỗ trợ", description: "Linh hoạt theo nhu cầu dự án" },
  ],
  sections: {
    capabilitiesEyebrow: "Năng lực cốt lõi",
    capabilitiesTitle: "Từ thiết bị, dịch vụ kỹ thuật đến hạ tầng công nghệ tổng thể",
    capabilitiesDescription:
      "HPT TECH tập trung vào khả năng triển khai thực tế cho môi trường doanh nghiệp, trường học, bệnh viện và tổ chức.",
    processEyebrow: "Quy trình triển khai",
    processTitle: "Một quy trình rõ ràng để giảm rủi ro khi triển khai",
    processDescription: "Mỗi bước được chuẩn hóa để khách hàng nắm được phạm vi, tiến độ và trách nhiệm kỹ thuật.",
    partnersEyebrow: "Đối tác & thương hiệu",
    partnersTitle: "Danh mục thương hiệu phục vụ nhu cầu triển khai đa dạng",
    partnersDescription: "Logo có thể được quản trị trong Payload để thay đổi theo danh mục đối tác thực tế.",
    advantagesEyebrow: "Năng lực cạnh tranh",
    advantagesTitle: "Điểm khác biệt nằm ở khả năng tư vấn và triển khai trọn gói",
    advantagesDescription:
      "HPT TECH không chỉ bán thiết bị, mà hỗ trợ doanh nghiệp chọn đúng giải pháp và vận hành ổn định.",
    caseStudiesEyebrow: "Dự án & khách hàng tiêu biểu",
    caseStudiesTitle: "Kinh nghiệm triển khai trong nhiều môi trường vận hành",
    caseStudiesDescription: "Các nhóm dự án có thể được mở rộng từ Payload khi HPT cập nhật case study thực tế.",
  },
  capabilities: [
    {
      title: "Cung cấp thiết bị công nghệ",
      description: "Danh mục thiết bị đầy đủ cho văn phòng, giáo dục, vận hành và hạ tầng CNTT.",
      items: [
        { label: "Laptop" },
        { label: "Máy tính để bàn" },
        { label: "Máy chủ" },
        { label: "NAS" },
        { label: "Máy in" },
        { label: "Máy photocopy" },
        { label: "Máy scan" },
        { label: "Thiết bị mạng" },
        { label: "Camera giám sát" },
        { label: "Thiết bị hội nghị" },
        { label: "Thiết bị giáo dục" },
        { label: "Thiết bị âm thanh trình chiếu" },
        { label: "Máy hủy tài liệu" },
        { label: "Máy in mã vạch" },
        { label: "Máy quét mã vạch" },
        { label: "Thiết bị nhận dạng" },
        { label: "Chấm công" },
        { label: "Kiểm soát ra vào" },
      ],
    },
    {
      title: "Dịch vụ kỹ thuật",
      description: "Đội ngũ kỹ thuật hỗ trợ từ tư vấn, thiết kế, tích hợp đến vận hành sau triển khai.",
      items: [
        { label: "Bảo trì thiết bị CNTT" },
        { label: "Sửa chữa thiết bị CNTT" },
        { label: "Tư vấn giải pháp công nghệ" },
        { label: "Thiết kế hệ thống" },
        { label: "Tích hợp hệ thống" },
        { label: "Giải pháp số hóa" },
        { label: "Hỗ trợ kỹ thuật" },
      ],
    },
    {
      title: "Đầu tư và xây dựng hạ tầng công nghệ",
      description: "Triển khai hạ tầng tổng thể cho văn phòng, nhà máy, trường học và tổ chức.",
      items: [
        { label: "Hạ tầng điện nhẹ" },
        { label: "LAN" },
        { label: "WiFi" },
        { label: "CCTV" },
        { label: "Âm thanh hội nghị" },
        { label: "Data Center" },
        { label: "Hạ tầng CNTT tổng thể" },
      ],
    },
  ],
  process: [
    { title: "Khảo sát", description: "Ghi nhận hiện trạng, nhu cầu vận hành và ràng buộc kỹ thuật." },
    { title: "Tư vấn giải pháp", description: "Đề xuất phương án phù hợp ngân sách và mục tiêu sử dụng." },
    { title: "Thiết kế & đề xuất", description: "Chuẩn hóa cấu hình, phạm vi triển khai và kế hoạch thực hiện." },
    { title: "Triển khai & lắp đặt", description: "Thi công, cấu hình, tích hợp và kiểm thử tại điểm triển khai." },
    { title: "Đào tạo & bàn giao", description: "Bàn giao tài liệu, hướng dẫn vận hành và nghiệm thu." },
    { title: "Bảo trì & hỗ trợ", description: "Theo dõi, xử lý sự cố và hỗ trợ kỹ thuật sau dự án." },
  ],
  partners: [
    { name: "HP" },
    { name: "Dell" },
    { name: "Lenovo" },
    { name: "HPE" },
    { name: "Brother" },
    { name: "Canon" },
    { name: "Epson" },
    { name: "Konica Minolta" },
    { name: "Microtek" },
    { name: "Joyusing" },
    { name: "OKI" },
  ],
  advantages: [
    { title: "Nguồn hàng chính hãng", description: "Tư vấn cấu hình rõ ràng, xuất xứ minh bạch và chứng từ đầy đủ." },
    { title: "Đội ngũ kỹ sư giàu kinh nghiệm", description: "Am hiểu thiết bị, hạ tầng và môi trường vận hành doanh nghiệp." },
    { title: "Triển khai toàn quốc", description: "Linh hoạt điều phối kỹ thuật theo quy mô và địa điểm dự án." },
    { title: "Hỗ trợ kỹ thuật nhanh chóng", description: "Tiếp nhận yêu cầu, xử lý sự cố và duy trì hoạt động ổn định." },
    { title: "Giải pháp tổng thể", description: "Kết hợp thiết bị, phần mềm, hạ tầng và dịch vụ sau bán hàng." },
  ],
  caseStudies: [
    { segment: "Doanh nghiệp", title: "Hệ thống máy chủ & hạ tầng", summary: "Tư vấn, cung cấp và triển khai hạ tầng CNTT phục vụ vận hành nội bộ." },
    { segment: "Trường học", title: "Thiết bị giáo dục", summary: "Trang bị thiết bị giảng dạy, máy tính, trình chiếu và hạ tầng lớp học." },
    { segment: "Bệnh viện", title: "Số hóa hồ sơ", summary: "Tối ưu quy trình lưu trữ, scan, quản lý tài liệu và khai thác dữ liệu." },
    { segment: "Cơ quan nhà nước", title: "LAN, CCTV, hội nghị", summary: "Triển khai hạ tầng mạng, an ninh và phòng họp trực tuyến." },
  ],
  cta: {
    title: "Bạn đang tìm kiếm giải pháp công nghệ cho doanh nghiệp?",
    description: "HPT TECH sẵn sàng khảo sát nhu cầu và đề xuất phương án triển khai phù hợp.",
    primaryCtaLabel: "Liên hệ tư vấn",
    primaryCtaHref: "/lien-he",
    secondaryCtaLabel: "Gọi ngay",
    secondaryCtaHref: "tel:0967286889",
  },
};

const listItemField: Field = {
  name: "items",
  label: "Danh sách nội dung",
  type: "array",
  fields: [{ name: "label", label: "Nội dung", type: "text", required: true }],
};

export const AboutPage: GlobalConfig = {
  slug: "about-page",
  label: "Trang giới thiệu",
  access: {
    read: () => true,
  },
  admin: {
    group: "Nội dung website",
  },
  hooks: {
    afterRead: [({ doc }) => ({ ...defaultAboutPage, ...(doc || {}) })],
    afterChange: [revalidateGlobal],
  },
  fields: [
    {
      name: "hero",
      label: "Hero",
      type: "group",
      defaultValue: defaultAboutPage.hero,
      fields: [
        { name: "title", label: "Tiêu đề", type: "text", required: true },
        { name: "description", label: "Mô tả", type: "textarea", required: true },
        { name: "backgroundImage", label: "Ảnh nền thực tế", type: "upload", relationTo: "media" },
        { name: "primaryCtaLabel", label: "Nút chính", type: "text" },
        { name: "primaryCtaHref", label: "Link nút chính", type: "text" },
        { name: "secondaryCtaLabel", label: "Nút phụ", type: "text" },
        { name: "secondaryCtaHref", label: "Link nút phụ", type: "text" },
      ],
    },
    {
      name: "stats",
      label: "Số liệu năng lực",
      type: "array",
      defaultValue: defaultAboutPage.stats,
      fields: [
        { name: "value", label: "Số liệu", type: "text", required: true },
        { name: "label", label: "Nhãn", type: "text", required: true },
        { name: "description", label: "Mô tả ngắn", type: "text" },
      ],
    },
    {
      name: "sections",
      label: "Tiêu đề các khu vực",
      type: "group",
      defaultValue: defaultAboutPage.sections,
      fields: [
        { name: "capabilitiesEyebrow", label: "Eyebrow - Năng lực", type: "text" },
        { name: "capabilitiesTitle", label: "Tiêu đề - Năng lực", type: "text" },
        { name: "capabilitiesDescription", label: "Mô tả - Năng lực", type: "textarea" },
        { name: "processEyebrow", label: "Eyebrow - Quy trình", type: "text" },
        { name: "processTitle", label: "Tiêu đề - Quy trình", type: "text" },
        { name: "processDescription", label: "Mô tả - Quy trình", type: "textarea" },
        { name: "partnersEyebrow", label: "Eyebrow - Đối tác", type: "text" },
        { name: "partnersTitle", label: "Tiêu đề - Đối tác", type: "text" },
        { name: "partnersDescription", label: "Mô tả - Đối tác", type: "textarea" },
        { name: "advantagesEyebrow", label: "Eyebrow - Cạnh tranh", type: "text" },
        { name: "advantagesTitle", label: "Tiêu đề - Cạnh tranh", type: "text" },
        { name: "advantagesDescription", label: "Mô tả - Cạnh tranh", type: "textarea" },
        { name: "caseStudiesEyebrow", label: "Eyebrow - Dự án", type: "text" },
        { name: "caseStudiesTitle", label: "Tiêu đề - Dự án", type: "text" },
        { name: "caseStudiesDescription", label: "Mô tả - Dự án", type: "textarea" },
      ],
    },
    {
      name: "capabilities",
      label: "Năng lực cốt lõi",
      type: "array",
      defaultValue: defaultAboutPage.capabilities,
      fields: [
        { name: "title", label: "Tiêu đề", type: "text", required: true },
        { name: "description", label: "Mô tả", type: "textarea" },
        { name: "image", label: "Ảnh thực tế", type: "upload", relationTo: "media" },
        listItemField,
      ],
    },
    {
      name: "process",
      label: "Quy trình triển khai",
      type: "array",
      defaultValue: defaultAboutPage.process,
      fields: [
        { name: "title", label: "Bước", type: "text", required: true },
        { name: "description", label: "Mô tả", type: "textarea" },
      ],
    },
    {
      name: "partners",
      label: "Đối tác & thương hiệu",
      type: "array",
      defaultValue: defaultAboutPage.partners,
      fields: [
        { name: "name", label: "Tên thương hiệu", type: "text", required: true },
        { name: "logo", label: "Logo", type: "upload", relationTo: "media" },
        { name: "url", label: "Website", type: "text" },
      ],
    },
    {
      name: "advantages",
      label: "Năng lực cạnh tranh",
      type: "array",
      defaultValue: defaultAboutPage.advantages,
      fields: [
        { name: "title", label: "Tiêu đề", type: "text", required: true },
        { name: "description", label: "Mô tả", type: "textarea" },
      ],
    },
    {
      name: "caseStudies",
      label: "Dự án & khách hàng tiêu biểu",
      type: "array",
      defaultValue: defaultAboutPage.caseStudies,
      fields: [
        { name: "segment", label: "Nhóm khách hàng", type: "text", required: true },
        { name: "title", label: "Tên dự án / năng lực", type: "text", required: true },
        { name: "summary", label: "Mô tả", type: "textarea" },
        { name: "image", label: "Ảnh minh họa", type: "upload", relationTo: "media" },
      ],
    },
    {
      name: "cta",
      label: "CTA cuối trang",
      type: "group",
      defaultValue: defaultAboutPage.cta,
      fields: [
        { name: "title", label: "Tiêu đề", type: "text", required: true },
        { name: "description", label: "Mô tả", type: "textarea" },
        { name: "primaryCtaLabel", label: "Nút chính", type: "text" },
        { name: "primaryCtaHref", label: "Link nút chính", type: "text" },
        { name: "secondaryCtaLabel", label: "Nút phụ", type: "text" },
        { name: "secondaryCtaHref", label: "Link nút phụ", type: "text" },
      ],
    },
  ],
};
