export interface Product {
  title: string;
  detail: string;
  brand: string;
  price: string;
  tag?: string;
  category: string;
  image: string;
  href: string;
}

export interface Brand {
  name: string;
  logo: string;
}

export interface Post {
  title: string;
  date: string;
  image: string;
  href: string;
}

export interface Solution {
  title: string;
  description: string;
  icon: string;
}

export const HPT_DATA = {
  banners: [
    "/assets/herobanner/herobanner1.png",
  ],
  categories: [
    { name: "Laptop doanh nghiệp", icon: "laptop" },
    { name: "Máy tính để bàn", icon: "monitor" },
    { name: "Máy chủ & Storage", icon: "server" },
    { name: "Thiết bị mạng", icon: "network" },
    { name: "Thiết bị văn phòng", icon: "printer" },
    { name: "Thiết bị hội nghị", icon: "video" },
    { name: "Camera & An ninh", icon: "cctv" },
    { name: "Thiết bị giáo dục", icon: "graduation-cap" },
    { name: "Phần mềm bản quyền", icon: "badge-check" },
    { name: "Linh kiện & Phụ kiện", icon: "cable" },
    { name: "Máy in", icon: "printer" },
    { name: "Máy scan", icon: "scan-line" },
    { name: "Mực in & Vật tư", icon: "droplets" },
    { name: "Lưu trữ & Backup", icon: "hard-drive" },
    { name: "Dịch vụ kỹ thuật", icon: "wrench" },
    { name: "Giải pháp số hóa", icon: "workflow" },
    { name: "Máy photocopy", icon: "copy" },
    { name: "Máy chiếu", icon: "projector" },
    { name: "UPS & Nguồn điện", icon: "battery-charging" },
  ],
  productTabs: ["Nổi bật", "Máy scan", "Máy in", "Thiết bị văn phòng", "HP", "Brother"],
  products: [
    {
      title: "Máy scan Ricoh IX1300",
      detail: "WiFi, nhỏ gọn, tốc độ cao cho văn phòng hiện đại",
      brand: "Ricoh",
      price: "15.500.000đ",
      tag: "Mới",
      category: "Máy scan",
      image: "https://hpttech.vn/media/144/catalog/Ricoh-IX1300.jpg?size=380",
      href: "https://hpttech.vn/may-scan-ricoh-ix1300-thiet-ke-nho-gon-hieu-suat-cao-ket-noi-linh-hoat/",
    },
    {
      title: "Máy scan Ricoh SP1425",
      detail: "ADF và Flatbed linh hoạt, tối ưu xử lý tài liệu",
      brand: "Ricoh",
      price: "14.000.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/146/catalog/Ricoh-SP1425.jpg?size=380",
      href: "https://hpttech.vn/may-scan-ricoh-sp1425-ket-hop-adf-va-flatbed-linh-hoat-toi-uu-hoa-xu-ly-tai-lieu-van-phong/",
    },
    {
      title: "Máy scan Ricoh fi-7480",
      detail: "Scan A3, 2 mặt tự động, tốc độ cao cho doanh nghiệp",
      brand: "Ricoh",
      price: "120.000.000đ",
      tag: "Cao cấp",
      category: "Máy scan",
      image: "https://hpttech.vn/media/150/catalog/Ricoh-fi-7480.jpg?size=380",
      href: "https://hpttech.vn/may-scan-kho-a3-ricoh-fi-7480-toi-uu-hoa-quy-trinh-so-hoa-tai-lieu-kho-lon/",
    },
    {
      title: "Brother DS-740D",
      detail: "Máy quét tài liệu di động 2 mặt tự động",
      brand: "Brother",
      price: "5.434.000đ",
      tag: "Bán chạy",
      category: "Máy scan",
      image: "https://hpttech.vn/media/173/catalog/BROTHER-DS-740D.jpg?size=380",
      href: "https://hpttech.vn/may-scan-brother-ds-740d/",
    },
    {
      title: "Plustek SmartOffice PS286 Plus",
      detail: "Máy quét tài liệu 2 mặt tự động, tốc độ cao",
      brand: "Plustek",
      price: "6.710.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/234/catalog/Giai-phap-van-phong-Plustek-Scanner-SmartOffice-PS286-Plus.png?size=380",
      href: "https://hpttech.vn/plustek-scanner-smartoffice-ps286-plus/",
    },
    {
      title: "HP ScanJet Enterprise Flow 7500",
      detail: "Máy quét phẳng & ADF công suất cao",
      brand: "HP",
      price: "32.524.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/277/catalog/L2725B.png?size=380",
      href: "https://hpttech.vn/hp-scanjet-enterprise-flow-7500-flatbed-scanner-l2725b/",
    },
    {
      title: "Brother DCP-B7620DW",
      detail: "Máy in Laser trắng đen đa năng, WiFi, in 2 mặt",
      brand: "Brother",
      price: "5.800.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/29/catalog/Brother-DCP-B7620DW.jpg?size=380",
      href: "https://hpttech.vn/may-in-laser-trang-den-da-nang-brother-dcp-b7620dw-in-2-mat-tu-dong-in-wifi-toc-do-cao/",
    },
    {
      title: "Epson WorkForce DS-970",
      detail: "Máy quét tài liệu 2 mặt tự động tốc độ cao",
      brand: "Epson",
      price: "25.000.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/334/catalog/Epson%20WorkForce%20DS-970.png?size=380",
      href: "https://hpttech.vn/may-scan-epson-workforce-ds-970-may-quet-tai-lieu-2-mat-tu-dong-toc-do-cao-cho-van-phong-doanh-nghiep/",
    },
    {
      title: "Brother DS-620",
      detail: "Máy quét tài liệu di động nhỏ gọn, cấp nguồn USB",
      brand: "Brother",
      price: "4.750.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/172/catalog/Brother-DS-620.png?size=380",
      href: "https://hpttech.vn/may-scan-brother-ds-620/",
    },
    {
      title: "Plustek MobileOffice AD480",
      detail: "Máy quét tài liệu 2 mặt tự động cho văn phòng",
      brand: "Plustek",
      price: "6.160.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/236/catalog/Giai-phap-van-phong-Plustek-Scanner-MobileOffice-AD480.png?size=380",
      href: "https://hpttech.vn/plustek-scanner-mobileoffice-ad480/",
    },
    {
      title: "HP ScanJet N9120 fn2",
      detail: "Máy quét A3 phẳng & ADF, công suất rất cao",
      brand: "HP",
      price: "84.700.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/275/catalog/L2763A.png?size=380",
      href: "https://hpttech.vn/hp-scanjet-enterprise-flow-n9120-fn2-document-scanner-l2763a/",
    },
    {
      title: "Microtek S6570",
      detail: "Máy quét tài liệu A3 tốc độ cao",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/373/catalog/Microtek-S6570-1.jpg?size=380",
      href: "https://hpttech.vn/may-scan-microtek-s6570-may-quet-tai-lieu/",
    },
    {
      title: "Microtek S8570",
      detail: "Máy quét tài liệu 2 mặt tốc độ cao khổ A3",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/374/catalog/Microtek-S8790-1.jpg?size=380",
      href: "https://hpttech.vn/may-scan-microtek-s8570-may-quet-tai-lieu-2-mat-tu-dong-toc-do-cao-kho-a3/",
    },
    {
      title: "Microtek S500DC",
      detail: "Máy quét màu 2 mặt tốc độ cao khổ A3",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/375/catalog/Microtek-S500DC-1.jpg?size=380",
      href: "https://hpttech.vn/may-scan-microtek-s500dc-may-quet-mau-2-mat-toc-do-cao-kho-a3/",
    },
    {
      title: "Microtek DI 7200S",
      detail: "Máy quét tài liệu 2 mặt tự động khổ A4",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/379/catalog/Microtek-ArtixScan-DI-7200S.jpg?size=380",
      href: "https://hpttech.vn/may-scan-microtek-artixscan-di-7200s-may-quet-tai-lieu-2-mat-tu-dong-toc-do-cao-kho-a4-cho-van-phong/",
    },
    {
      title: "Microtek DI 6260S",
      detail: "Máy quét tài liệu ADF 2 mặt tốc độ cao",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/380/catalog/Microtek-ArtixScan-DI-6260S.avif?size=380",
      href: "https://hpttech.vn/may-scan-microtek-artixscan-di-6260s-may-quet-tai-lieu-adf-2-mat-toc-do-cao-cho-van-phong/",
    },
    {
      title: "Microtek DI 5240",
      detail: "Máy quét tài liệu 2 mặt tự động ADF khổ A4",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/385/catalog/Microtek-ArtixScan-DI-5240.jpg?size=380",
      href: "https://hpttech.vn/may-scan-microtek-artixscan-di-5240-may-quet-tai-lieu-2-mat-tu-dong-adf-kho-a4-cho-van-phong-doanh-nghiep/",
    },
    {
      title: "Brother HL-B2080DW",
      detail: "Máy in laser, in 2 mặt tự động, kết nối WiFi",
      brand: "Brother",
      price: "3.990.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/30/catalog/Brother-HL-B2080DW.png?size=380",
      href: "https://hpttech.vn/may-in-laser-brother-hl-b2080dw-in-2-mat-tu-dong-ket-noi-wifi-chinh-hang/",
    },
    {
      title: "Epson WorkForce DS-790WN",
      detail: "Máy quét tài liệu A4 duplex sheet-fed",
      brand: "Epson",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/119/catalog/Epson-WorkForce-DS-790WN.png?size=380",
      href: "https://hpttech.vn/may-scan-epson-workforce-ds-790wn-may-quet-tai-lieu-a4-toc-do-cao-duplex-sheet-fed/",
    },
    {
      title: "Ricoh fi-7460",
      detail: "Giải pháp số hóa tài liệu khổ lớn chuyên nghiệp",
      brand: "Ricoh",
      price: "72.000.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/151/catalog/Ricoh-fi-7460.jpg?size=380",
      href: "https://hpttech.vn/may-scan-kho-a3-ricoh-fi-7460-giai-phap-so-hoa-tai-lieu-kho-lon-nhanh-chong-va-chuyen-nghiep/",
    },
    {
      title: "Canon imageFORMULA R40",
      detail: "Máy scan tài liệu A4, nạp giấy tự động cho văn phòng",
      brand: "Canon",
      price: "7.900.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Canon imageFORMULA DR-C240",
      detail: "Máy quét tài liệu tốc độ cao, xử lý giấy linh hoạt",
      brand: "Canon",
      price: "18.500.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Kodak ScanMate i940",
      detail: "Máy scan nhỏ gọn cho cá nhân và nhóm làm việc",
      brand: "Kodak",
      price: "6.500.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Kodak Alaris S2050",
      detail: "Máy quét tài liệu tốc độ cao cho doanh nghiệp",
      brand: "Kodak",
      price: "21.900.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Avision AD345",
      detail: "Máy scan ADF 2 mặt, tối ưu số hóa hồ sơ",
      brand: "Avision",
      price: "9.800.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Avision AN360W",
      detail: "Máy quét tài liệu kết nối mạng và WiFi",
      brand: "Avision",
      price: "12.900.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Fujitsu ScanSnap iX1600",
      detail: "Máy scan văn phòng màn hình cảm ứng, WiFi",
      brand: "Fujitsu",
      price: "13.990.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Fujitsu fi-8170",
      detail: "Máy scan doanh nghiệp tốc độ cao, độ bền lớn",
      brand: "Fujitsu",
      price: "29.900.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "HP LaserJet Pro 4003dn",
      detail: "Máy in laser đơn năng, in đảo mặt tự động",
      brand: "HP",
      price: "5.490.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "HP LaserJet MFP 4103fdw",
      detail: "Máy in đa năng, scan, copy, fax, WiFi",
      brand: "HP",
      price: "9.990.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Epson EcoTank L6270",
      detail: "Máy in phun màu đa năng, bình mực tiết kiệm",
      brand: "Epson",
      price: "8.290.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Epson WorkForce Pro WF-C5890",
      detail: "Máy in doanh nghiệp hiệu suất cao, chi phí thấp",
      brand: "Epson",
      price: "12.490.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Brother MFC-L5900DW",
      detail: "Máy in đa năng laser trắng đen cho văn phòng",
      brand: "Brother",
      price: "10.900.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Brother HL-L6200DW",
      detail: "Máy in laser tốc độ cao, WiFi, duplex",
      brand: "Brother",
      price: "8.700.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Pantum BM5100ADW",
      detail: "Máy in đa năng laser, in mạng không dây",
      brand: "Pantum",
      price: "6.990.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "OKI B432dn",
      detail: "Máy in laser trắng đen, tốc độ cao cho văn phòng",
      brand: "OKI",
      price: "7.500.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Kyocera ECOSYS M2040dn",
      detail: "Máy in đa năng bền bỉ, chi phí vận hành thấp",
      brand: "Kyocera",
      price: "13.500.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Plustek eScan A350",
      detail: "Máy scan mạng độc lập, màn hình cảm ứng",
      brand: "Plustek",
      price: "24.900.000đ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Microtek ScanMaker 9800XL",
      detail: "Máy scan flatbed khổ lớn cho hồ sơ và bản vẽ",
      brand: "Microtek",
      price: "Liên hệ",
      category: "Máy scan",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
    {
      title: "Fujifilm Apeos C325dw",
      detail: "Máy in màu laser compact cho văn phòng hiện đại",
      brand: "Fujifilm",
      price: "11.900.000đ",
      category: "Máy in",
      image: "https://hpttech.vn/media/0/default-image.png?size=512",
      href: "https://hpttech.vn/",
    },
  ],
  brands: [
    { name: "Avision", logo: "assets/brands/avision.svg" },
    { name: "Brother", logo: "assets/brands/brother.svg" },
    { name: "Canon", logo: "assets/brands/canon.svg" },
    { name: "Epson", logo: "assets/brands/epson.svg" },
    { name: "Fujifilm", logo: "assets/brands/fujifilm.svg" },
    { name: "Fujitsu", logo: "assets/brands/fujitsu.svg" },
    { name: "HP", logo: "assets/brands/hp.svg" },
    { name: "Kodak", logo: "assets/brands/kodak.svg" },
    { name: "Minolta", logo: "assets/brands/minolta.svg" },
    { name: "Kyocera", logo: "assets/brands/kyocera.svg" },
    { name: "Microtek", logo: "assets/brands/microtek.svg" },
    { name: "OJI Paper", logo: "assets/brands/oji-paper.svg" },
    { name: "OKI", logo: "assets/brands/oki.svg" },
    { name: "Pantum", logo: "assets/brands/pantum.svg" },
    { name: "PaperOne", logo: "assets/brands/paperone.svg" },
    { name: "Plustek", logo: "assets/brands/plustek.svg" },
  ],
  solutions: [
    { title: "Hạ tầng CNTT", description: "Tư vấn, thiết kế và triển khai hệ thống hạ tầng CNTT đồng bộ, ổn định và an toàn.", icon: "blocks" },
    { title: "An ninh & Camera", description: "Triển khai CCTV, kiểm soát ra vào và giám sát tập trung cho doanh nghiệp.", icon: "shield" },
    { title: "Giải pháp hội nghị", description: "Thiết bị họp trực tuyến, âm thanh, trình chiếu và phòng họp thông minh.", icon: "video" },
    { title: "Giáo dục thông minh", description: "Màn hình tương tác, camera vật thể và thiết bị lớp học số.", icon: "graduation-cap" },
  ],
  posts: [
    {
      title: "Visioneer Organizer AI: Phần Mềm AI Giúp Máy Scan Tự Phân Loại và Quản Lý Tài Liệu Số",
      date: "25 Tháng Năm, 2026",
      image: "/assets/commercial-blocks/solution.jpg",
      href: "https://hpttech.vn/visioneer-organizer-ai-phan-mem-quan-ly-tai-lieu-thong-minh/",
    },
    {
      title: "Làm thế nào để chọn máy Scan phù hợp nhất cho doanh nghiệp năm 2026",
      date: "23 Tháng Năm, 2026",
      image: "/assets/commercial-blocks/scanner.jpg",
      href: "https://hpttech.vn/cach-chon-may-scan-phu-hop-nam-2026/",
    },
    {
      title: "Mapstore.vn - xây dựng bản đồ doanh nghiệp Việt Nam trong kỷ nguyên dữ liệu địa phương",
      date: "30 Tháng Giêng, 2026",
      image: "/assets/herobanner/herobanner3.png",
      href: "https://hpttech.vn/mapstore-vn-xay-dung-ban-do-doanh-nghiep-viet-nam-trong-ky-nguyen-du-lieu-dia-phuong/",
    },
    {
      title: "HP ProDesk 600 G2 SFF cho cửa hàng, quầy thu ngân và mô hình bán lẻ",
      date: "26 Tháng Giêng, 2026",
      image: "/assets/commercial-blocks/office.jpg",
      href: "https://hpttech.vn/hp-prodesk-600-g2-sff-cho-cua-hang-quay-thu-ngan-va-mo-hinh-ban-le/",
    },
  ],
};
