export const HPT_PRODUCT_SPECS: Record<string, Record<string, string>> = {
  "https://hpttech.vn/may-scan-ricoh-ix1300-thiet-ke-nho-gon-hieu-suat-cao-ket-noi-linh-hoat/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "30 trang/phút",
    "ADF": "20 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.2, Wi-Fi",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/may-scan-ricoh-sp1425-ket-hop-adf-va-flatbed-linh-hoat-toi-uu-hoa-xu-ly-tai-lieu-van-phong/": {
    "Khổ giấy": "A4 / Flatbed",
    "Tốc độ quét": "25 trang/phút",
    "ADF": "50 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 2.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/may-scan-kho-a3-ricoh-fi-7480-toi-uu-hoa-quy-trinh-so-hoa-tai-lieu-kho-lon/": {
    "Khổ giấy": "A3",
    "Tốc độ quét": "80 trang/phút",
    "ADF": "100 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/may-scan-brother-ds-740d/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "15 trang/phút",
    "ADF": "Nạp tay từng tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.0",
    "Nguồn điện": "Qua cổng USB",
  },
  "https://hpttech.vn/plustek-scanner-smartoffice-ps286-plus/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "25 trang/phút",
    "ADF": "50 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 2.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/hp-scanjet-enterprise-flow-7500-flatbed-scanner-l2725b/": {
    "Khổ giấy": "A4 / Flatbed",
    "Tốc độ quét": "50 trang/phút",
    "ADF": "100 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 2.0",
    "Công suất ngày": "4.000 trang",
  },
  "https://hpttech.vn/may-in-laser-trang-den-da-nang-brother-dcp-b7620dw-in-2-mat-tu-dong-in-wifi-toc-do-cao/": {
    "Loại máy": "Laser trắng đen đa năng",
    "Tốc độ in": "34 trang/phút",
    "In hai mặt": "Tự động",
    "Kết nối": "USB, LAN, Wi-Fi",
    "Chức năng": "In, scan, copy",
    "Khổ giấy": "A4",
  },
  "https://hpttech.vn/may-scan-epson-workforce-ds-970-may-quet-tai-lieu-2-mat-tu-dong-toc-do-cao-cho-van-phong-doanh-nghiep/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "85 trang/phút",
    "ADF": "100 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.0",
    "Công suất ngày": "9.000 trang",
  },
  "https://hpttech.vn/may-scan-brother-ds-620/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "8 trang/phút",
    "ADF": "Nạp tay từng tờ",
    "Quét hai mặt": "Không",
    "Kết nối": "USB 2.0",
    "Nguồn điện": "Qua cổng USB",
  },
  "https://hpttech.vn/plustek-scanner-mobileoffice-ad480/": {
    "Khổ giấy": "A4",
    "Tốc độ quét": "20 trang/phút",
    "ADF": "20 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 2.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/hp-scanjet-enterprise-flow-n9120-fn2-document-scanner-l2763a/": {
    "Khổ giấy": "A3 / Flatbed",
    "Tốc độ quét": "50 trang/phút",
    "ADF": "200 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB, LAN",
    "Công suất ngày": "10.000 trang",
  },
  "https://hpttech.vn/may-scan-microtek-s6570-may-quet-tai-lieu/": {
    "Khổ giấy": "A3",
    "Tốc độ quét": "65 trang/phút",
    "ADF": "100 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/may-scan-microtek-s8570-may-quet-tai-lieu-2-mat-tu-dong-toc-do-cao-kho-a3/": {
    "Khổ giấy": "A3",
    "Tốc độ quét": "85 trang/phút",
    "ADF": "100 tờ",
    "Quét hai mặt": "Có",
    "Kết nối": "USB 3.0",
    "Độ phân giải quang học": "600 dpi",
  },
  "https://hpttech.vn/may-in-laser-brother-hl-b2080dw-in-2-mat-tu-dong-ket-noi-wifi-chinh-hang/": {
    "Loại máy": "Laser trắng đen đơn năng",
    "Tốc độ in": "34 trang/phút",
    "In hai mặt": "Tự động",
    "Kết nối": "USB, Wi-Fi",
    "Bộ nhớ": "128 MB",
    "Khổ giấy": "A4",
  },
};