import type { BrandConfig } from "../types";

export const brandConfigs = [
  {
    aliases: ["openai", "chatgpt"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "openai.com",
    extraDomains: ["chatgpt.com"],
    name: "OpenAI",
    slug: "openai",
  },
  {
    aliases: ["autodesk", "autocad", "revit", "navisworks", "inventor", "advance steel", "product design & manufacturing"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "autodesk.com",
    extraDomains: ["autodesk.com"],
    name: "Autodesk",
    slug: "autodesk",
  },
  {
    aliases: ["adobe", "acrobat", "photoshop", "illustrator", "indesign", "lightroom", "premiere", "creative cloud"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "adobe.com",
    extraDomains: ["adobe.com"],
    name: "Adobe",
    slug: "adobe",
  },
  {
    aliases: ["canva"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "canva.com",
    extraDomains: ["canva.com"],
    name: "Canva",
    slug: "canva",
  },
  {
    aliases: ["capcut"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "capcut.com",
    extraDomains: ["capcut.com"],
    name: "CapCut",
    slug: "capcut",
  },
  {
    aliases: ["teamviewer"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "teamviewer.com",
    extraDomains: ["teamviewer.com"],
    name: "TeamViewer",
    slug: "teamviewer",
  },
  {
    aliases: ["corel", "graphics suite"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "corel.com",
    extraDomains: ["coreldraw.com"],
    name: "Corel",
    slug: "corel",
  },
  {
    aliases: ["bitdefender"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "bitdefender.com",
    extraDomains: ["bitdefender.com"],
    name: "Bitdefender",
    slug: "bitdefender",
  },
  {
    aliases: ["bullguard"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "bullguard.com",
    extraDomains: ["norton.com"],
    name: "BullGuard",
    slug: "bullguard",
  },
  {
    aliases: ["trend micro"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "trendmicro.com",
    extraDomains: ["trendmicro.com"],
    name: "Trend Micro",
    slug: "trend-micro",
  },
  {
    aliases: ["microsoft", "micrsoft", "m365", "office", "windows", "win home"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "microsoft.com",
    extraDomains: ["microsoft.com"],
    name: "Microsoft",
    slug: "microsoft",
  },
  {
    aliases: ["kaspersky"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "kaspersky.com",
    extraDomains: ["kaspersky.com.vn"],
    name: "Kaspersky",
    slug: "kaspersky",
  },
  {
    aliases: ["bkav"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "bkav.com.vn",
    extraDomains: ["bkav.com"],
    name: "Bkav",
    slug: "bkav",
  },
  {
    aliases: ["draytek"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "draytek.com",
    extraDomains: ["draytek.com.vn"],
    name: "DrayTek",
    slug: "draytek",
  },
  {
    aliases: ["laptop asus", "asus", "asuswrt"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "asus.com",
    extraDomains: ["asus.com", "asus.com.vn"],
    name: "ASUS",
    slug: "asus",
  },
  {
    aliases: ["laptop gigabyte", "gigabyte", "aorus"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "gigabyte.com",
    extraDomains: ["gigabyte.com", "aorus.com"],
    name: "Gigabyte",
    slug: "gigabyte",
  },
  {
    aliases: ["laptop msi", "msi", "katana", "cyborg", "thin", "stealth", "raider"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "msi.com",
    extraDomains: ["msi.com", "msi.com/Laptop"],
    name: "MSI",
    slug: "msi",
  },
  {
    aliases: ["laptop acer", "acer", "predator", "nitro", "aspire", "swift"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "acer.com",
    extraDomains: ["acer.com", "acer.com/vn-vi"],
    name: "Acer",
    slug: "acer",
  },
  {
    aliases: ["laptop lenovo", "lenovo", "legion", "loq", "thinkpad", "ideapad", "yoga"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "lenovo.com",
    extraDomains: ["lenovo.com", "lenovo.com/vn"],
    name: "Lenovo",
    slug: "lenovo",
  },
  {
    aliases: ["laptop dell", "dell", "alienware", "inspiron", "vostro", "latitude", "precision", "xps", "g15", "g16"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "dell.com",
    extraDomains: ["dell.com", "dell.com/en-vn"],
    name: "Dell",
    slug: "dell",
  },
  {
    aliases: ["laptop hp", "hp laptop", "omen", "victus", "pavilion", "envy", "spectre", "elitebook", "probook", "zbook"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "hp.com",
    extraDomains: ["hp.com", "hp.com/vn-vi"],
    name: "HP",
    slug: "hp-laptop",
  },
  {
    aliases: ["laptop apple", "macbook", "macbook air", "macbook pro"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "apple.com",
    extraDomains: ["apple.com", "apple.com/vn"],
    name: "Apple",
    slug: "apple",
  },
  {
    aliases: ["laptop lg", "lg gram", "gram"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "lg.com",
    extraDomains: ["lg.com", "lg.com/vn"],
    name: "LG",
    slug: "lg",
  },
  {
    aliases: ["laptop samsung", "galaxy book", "samsung"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "samsung.com",
    extraDomains: ["samsung.com", "samsung.com/vn"],
    name: "Samsung",
    slug: "samsung",
  },
  {
    aliases: ["laptop huawei", "matebook", "huawei"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "huawei.com",
    extraDomains: ["huawei.com", "consumer.huawei.com"],
    name: "Huawei",
    slug: "huawei",
  },
  {
    aliases: ["surface laptop", "surface pro", "surface book", "surface"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "microsoft.com",
    extraDomains: ["microsoft.com"],
    name: "Microsoft Surface",
    slug: "microsoft-surface",
  },
  {
    aliases: ["tp-link", "tplink", "deco", "omada", "mercusys"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "tp-link.com",
    extraDomains: ["tp-link.com", "tp-link.com/vn", "mercusys.com"],
    name: "TP-Link",
    slug: "tp-link",
  },
  {
    aliases: ["linksys"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "linksys.com",
    extraDomains: ["linksys.com"],
    name: "Linksys",
    slug: "linksys",
  },
  {
    aliases: ["ubiquiti", "unifi", "ui.com"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "ui.com",
    extraDomains: ["ui.com", "ubnt.com"],
    name: "Ubiquiti",
    slug: "ubiquiti",
  },
  {
    aliases: ["cisco"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "cisco.com",
    extraDomains: ["cisco.com"],
    name: "Cisco",
    slug: "cisco",
  },
  {
    aliases: ["planet"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "planet.com.tw",
    extraDomains: ["planet.com.tw"],
    name: "Planet",
    slug: "planet",
  },
  {
    aliases: ["grandstream"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "grandstream.com",
    extraDomains: ["grandstream.com"],
    name: "Grandstream",
    slug: "grandstream",
  },
  {
    aliases: ["hpe aruba", "aruba"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "arubanetworks.com",
    extraDomains: ["arubanetworks.com", "hpe.com"],
    name: "HPE Aruba",
    slug: "hpe-aruba",
  },
  {
    aliases: ["h3c"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "h3c.com",
    extraDomains: ["h3c.com"],
    name: "H3C",
    slug: "h3c",
  },
  {
    aliases: ["dintek"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "dintek.com.tw",
    extraDomains: ["dintek.com.tw"],
    name: "Dintek",
    slug: "dintek",
  },
  {
    aliases: ["hikvision"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "hikvision.com",
    extraDomains: ["hikvision.com"],
    name: "Hikvision",
    slug: "hikvision",
  },
  {
    aliases: ["dahua"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "dahuasecurity.com",
    extraDomains: ["dahuasecurity.com"],
    name: "Dahua",
    slug: "dahua",
  },
  {
    aliases: ["ezviz"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "ezviz.com",
    extraDomains: ["ezviz.com"],
    name: "EZVIZ",
    slug: "ezviz",
  },
  {
    aliases: ["imou"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "imoulife.com",
    extraDomains: ["imoulife.com"],
    name: "IMOU",
    slug: "imou",
  },
  {
    aliases: ["kbvision", "kb vision"],
    crawlMethod: "fetch",
    delayMs: 1500,
    domain: "kbvision.vn",
    extraDomains: ["kbvision.vn"],
    name: "KBVision",
    slug: "kbvision",
  },
  {
    aliases: [
      "microtek",
      "artixscan",
      "filescan",
      "h-screen",
      "h‑screen",
      "objectscan",
      "scanmaker",
    ],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "microtek.com",
    extraDomains: ["microtek.com"],
    name: "Microtek",
    slug: "microtek",
  },
  {
    aliases: ["xerox"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "xerox.com",
    extraDomains: ["xerox.com"],
    name: "Xerox",
    slug: "xerox",
  },
  {
    aliases: ["fujifilm", "fuji"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "fujifilm.com",
    extraDomains: ["fujifilm.com"],
    name: "Fujifilm",
    slug: "fujifilm",
  },
  {
    aliases: ["avision"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "avision.com",
    extraDomains: ["avision.com"],
    name: "Avision",
    slug: "avision",
  },
  {
    aliases: ["plustek", "opticslim", "opticbook", "opticfilm"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "plustek.com",
    extraDomains: ["plustek.com"],
    name: "Plustek",
    slug: "plustek",
  },
  {
    aliases: ["kodak", "alaris", "scanmate"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "alarisworld.com",
    extraDomains: ["kodakalaris.com"],
    name: "Kodak Alaris",
    slug: "kodak-alaris",
  },
  {
    aliases: ["panasonic"],
    crawlMethod: "fetch",
    delayMs: 2500,
    domain: "panasonic.com/vn",
    extraDomains: ["panasonic.com"],
    name: "Panasonic",
    slug: "panasonic",
  },
  {
    aliases: ["epson", "ecotank"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "epson.com.vn",
    extraDomains: ["epson.com", "epson.eu", "support.epson.net"],
    name: "Epson",
    slug: "epson",
  },
  {
    aliases: ["ricoh", "fujitsu"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "ricoh.com.vn",
    extraDomains: ["ricoh.com", "ricoh-usa.com", "pfu.ricoh.com"],
    name: "Ricoh",
    slug: "ricoh",
  },
  {
    aliases: ["canon", "imageclass", "pixma", "maxify"],
    crawlMethod: "fetch",
    delayMs: 2500,
    domain: "vn.canon",
    extraDomains: ["canon.com", "usa.canon.com", "support.usa.canon.com"],
    name: "Canon",
    slug: "canon",
  },
  {
    aliases: ["konica", "minolta", "bizhub"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "konicaminolta.com",
    extraDomains: ["konicaminolta.com"],
    name: "Konica Minolta",
    slug: "konica-minolta",
  },
  {
    aliases: ["sharp"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "global.sharp",
    extraDomains: ["sharp.com"],
    name: "Sharp",
    slug: "sharp",
  },
  {
    aliases: ["brother"],
    crawlMethod: "playwright",
    delayMs: 3000,
    domain: "brother.com.vn",
    extraDomains: ["brother.com", "brother-usa.com", "brother.co.uk", "support.brother.com"],
    name: "Brother",
    slug: "brother",
  },
  {
    aliases: ["hp", "laserjet", "deskjet", "officejet"],
    crawlMethod: "playwright",
    delayMs: 4000,
    domain: "hp.com/vn-vi",
    extraDomains: ["hp.com", "support.hp.com"],
    name: "HP",
    slug: "hp",
  },
  {
    aliases: ["kyocera", "ecosys"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "kyoceradocumentsolutions.com",
    extraDomains: ["kyoceradocumentsolutions.com.vn"],
    name: "Kyocera",
    slug: "kyocera",
  },
  {
    aliases: ["xprinter", "xp-p"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "xprintertech.com",
    extraDomains: ["xprintertech.com"],
    name: "Xprinter",
    slug: "xprinter",
  },
  {
    aliases: ["pantum"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "pantum.com",
    extraDomains: ["pantum.com"],
    name: "Pantum",
    slug: "pantum",
  },
  {
    aliases: ["zebra"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "zebra.com",
    extraDomains: ["zebra.com"],
    name: "Zebra",
    slug: "zebra",
  },
  {
    aliases: ["apos", "apos-p", "apos-"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "anphatpc.com.vn",
    extraDomains: ["anphatpc.com.vn"],
    name: "APOS",
    slug: "apos",
  },
  {
    aliases: ["atp", "atp-"],
    crawlMethod: "fetch",
    delayMs: 2000,
    domain: "anphatpc.com.vn",
    extraDomains: ["anphatpc.com.vn"],
    name: "ATP",
    slug: "atp",
  },
] satisfies BrandConfig[];

export function findBrandByName(productName: string) {
  const normalized = productName.toLowerCase();
  return brandConfigs
    .flatMap((brand) =>
      brand.aliases
        .filter((alias) => normalized.includes(alias.toLowerCase()))
        .map((alias) => ({ alias, brand })),
    )
    .sort((a, b) => b.alias.length - a.alias.length)[0]?.brand;
}

export function findBrandBySlug(slug: string) {
  return brandConfigs.find((brand) => brand.slug === slug);
}

export function findBrandByUrl(url: string) {
  try {
    const hostname = new URL(url).hostname.replace(/^www\./, "");
    return brandConfigs.find((brand) => {
      const domain = brand.domain.replace(/^www\./, "").replace(/\/.*$/, "");
      return hostname.includes(domain);
    });
  } catch {
    return undefined;
  }
}
